// src/types/ai-analysis.ts

/**
 * Possible statuses for AI analysis workflow.
 */
export enum AIAnalysisStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NEEDS_HUMAN_REVIEW = 'NEEDS_HUMAN_REVIEW',
  FALLBACK = 'FALLBACK', // indicates fallback deterministic analysis
}

/**
 * Structured result of AI problem engine for a challenge.
 */
export interface AIChallengeAnalysis {
  analysisId: string; // unique identifier (e.g., ObjectId string)
  challengeId: string; // reference to the challenge.challengeId

  // AI suggested domain and confidence (0-1)
  suggestedDomain: string;
  domainConfidence: number;

  // AI suggested priority and confidence (0-1)
  suggestedPriority: string;
  priorityConfidence: number;

  // Human‑readable summary generated by AI
  problemSummary: string;

  // Population impact description (optional)
  affectedPopulation?: string;
  affectedPopulationEstimate?: string;

  // Impact and urgency levels (canonical enums)
  impactLevel: string;
  urgencyLevel: string;

  // Extracted structured information
  keyIssues: string[];
  keywords: string[];
  suggestedTags: string[];
  possibleCauses: string[];

  // Duplicate detection candidates
  duplicateCandidates: Array<{
    challengeId: string;
    similarityScore: number;
    reason: string;
  }>;
  duplicateConfidence: number;

  // Routing signals for future phases
  routingSignals: string[];
  requiredDisciplines: string[];
  relevantExpertise: string[];
  geographicRelevance?: string;

  // Concise reasoning for the AI decisions
  reasoning: string;

  // Provider metadata
  modelProvider?: string;
  modelName?: string;

  // Workflow status and timestamps
  status: AIAnalysisStatus;
  analyzedAt: Date;
  updatedAt: Date;
}
